- name: Update system packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install common packages
  ansible.builtin.package:
    name:
      - vim
      - curl
      - git
    state: present

- name: Install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: true


